name: ntsc_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dart_jsonwebtoken: ^3.2.0
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.3.0
  provider: ^6.1.5
  reorderables: ^0.6.0
  url_launcher: ^6.3.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
